version: '3'
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    networks:
      - payment-form-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
    networks:
      - payment-form-network
    depends_on:
      - mongo
  back-end:
    build:
      context: ./back-end/docker/development
    container_name: payment-form-back-end
    entrypoint: ['yarn', 'start']
    volumes:
      - ./back-end:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - mongo
    networks:
      - payment-form-network
    environment:
      mongoose_url: 'mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017'
      PORT: 8000

networks:
  payment-form-network:
    driver: bridge
